[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = admin_change_me
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
; Limit databases visible at /web/database/manager
list_db = True
; Dev convenience: lower workers for a single-machine POC
workers = 0
max_cron_threads = 1
